pydata/sparse

- sparse/core.py
- sparse/tests/test_core.py
This adds the ``elemwise_binary`` method that implements an efficient version of the logic needed to perform binary ufuncs where both operators are ``COO`` matrices (as long as ``func(0, 0)=0``).
Currently I only enabled ``__mul__`` and ``__rmul__``, but it should be straightforward to add more.
First commits use a KD Tree approach; the final commit changes this to a binary search within the lex-sorted coordinate array, which should be much faster.
> ENH: add logic for binary ufuncs

- sparse/core.py
- sparse/tests/test_core.py
- sparse/utils.py
This started by adding the optimzied version of tocsr from #9 (cc @jakevdp) 
Then, to avoid calling sorting routines excessively we started tracking `sorted=` metadata.
Then, to accelerate sorting and to consolidate lexsort and reshape code we based all sorting code onto a single function called `linear_loc`, which provides the linear location of any index in a C-ordered array.  This replaces `np.lexsort` with `np.argsort` and performs a quick `issorted` check beforehand.  This can dramatically speed up some workflows, but does limit the size of our arrays to `2**64` elements (zero or nonzero) so for example this library can no longer represent an array of shape `(1e6, 1e6, 1e6, 1e6)`.  This was already the case in reshape.  I'm personally ok with this for the time being.  I think that we …
> Optimize CSR and sorted conversions

- sparse/core.py
- sparse/tests/test_core.py
This supersedes the closed https://github.com/mrocklin/sparse/pull/14.
This request simply adds the `__matmul__` and `__rmatmul__` with no behavior other than that delegated to `sparse.dot()`.  Checks for "correct" non-combination of lists with COOs remains.  A more specific `return NotImplemented` is returned for things lacking an `.ndim`, which gives us a better error of:
```python
TypeError: unsupported operand type(s) for @: 'list' and 'COO'
```
> Add @ operator (simplify)

- MANIFEST.in
The current tarball distributed on PyPI is missing some files required for producing quality binary packages for Linux distributions.
In addition to the `README.rst` and package content, which `sdist` handles by default, this commit adds the licensing terms (also added by default if the file were named `LICENSE`) and the test suite, which is helpful for continuous integration purposes.
> Improve the source release for PyPI

- sparse/core.py
Basically, the test was failing because we weren't making `coords` and `data` 2-D and 1-D as expected by our code. This fixes those bugs with scalar slicing.
> Fix scalar slicing issue.

- .gitignore
I noticed that the current `.gitignore` file was pretty incomplete, not ignoring `*.egg` or `build` directories etc.
So I took the Gitignore file from [github/gitignore.git](https://github.com/github/gitignore/blob/master/Python.gitignore) and added it to this project.
> More complete gitignore file

- sparse/core.py
- sparse/tests/test_core.py
I've removed the auto-densification in `__add__` and `exp` and I've removed the tests for it. In addition, I've unified the code for all operators so that they only work when not densified. In addition, they work with scalars if the scalars don't densify them.
> Remove auto densification and unify operator code.

- sparse/core.py
> Fix nnz for scalars.

- sparse/core.py
- sparse/tests/test_core.py
> Fix large concatenations and stacks.

- .travis.yml
- setup.cfg
- setup.py
I totally missed that you guys were using `flake8` to keep the code style clean... To make it easier for first time contributors we could, instead of running `flake8` manually, integrate it into the `pytest` run.
> flake8 and coverage in pytest

- sparse/__init__.py
- sparse/core.py
- sparse/tests/test_core.py
- sparse/utils.py
I think a `random()` function is could be pretty handy for generating some quick testing data.
I tried several methods, like generating `.coords` and `.data` myself, and creating a `COO` object from them. In the end it turned out to be the easiest to create a linear `scipy.sparse` array and simply reshape it to the desired output shape.
> Add random() function

- sparse/core.py
- sparse/slicing.py
- sparse/tests/test_core.py
Adds support for:
- Returning scalars when slicing, e.g. `x[1, 1]` if `x` is 2-D is now scalar.
- Returning arrays when the last index is an `Ellipsis`, e.g. `x[1, 1, ...]` if `x` is 2-D is now a `()`-shaped `COO` object.
- Slices with steps other than `None` and `1` (even negative steps).
- Inbdexing with custom `dtype`s. So if `x` has a custom `dtype`, `x['field']` is now supported.
- Now throws `IndexError`s consistent with Numpy for string and out of range indices.
> Add lots of indexing features.

- sparse/core.py
- sparse/tests/test_core.py
Before this change `COO` arrays allowed many variants of illegal `.transpose()` parameters:
sparse.random((2, 3, 4)).transpose((0, 0, 1))  # duplicate axis
sparse.random((2, 3, 4)).transpose((0, 1))  # too few
sparse.random((2, 3, 4)).transpose((0, 1, 2, 3))  # too many
This PR adds some sanity checks and compares the exceptions of some scenarios with the exceptions from NumPy.
> Validate .transpose() axes

- sparse/tests/test_core.py
Fixes #63.
Actually, one test fails with a higher density.
> Use higher density for sparse.random in tests

- sparse/core.py
- sparse/tests/test_core.py
Fixes #66.
This adds a workaround when the np.number multiplication from left-side.
> Support left-side np.number elemwise operations.

- sparse/core.py
- sparse/tests/test_core.py
Quite trivial really, implements the `len()` operation following NumPy's convention of
len(array) == array.shape[0]
> len() function for COO objects

- sparse/tests/test_core.py
Prior to NumPy `1.13.0`, you would see a `VisibleDeprecationWarning` but no exception when using illegal indexing values. This makes test `test_slicing_errors[index6]` fail.
__________________________________ test_slicing_errors[index6] ____________________________________
index = [True, False, False]
@pytest.mark.parametrize('index', [
(Ellipsis, Ellipsis),
(1, 1, 1, 1),
(slice(None),) * 4,
5,
-5,
'foo',
([True, False, False]),
])
def test_slicing_errors(index):
s = sparse.random((2, 3, 4), density=0.5)
x = s.todense()
try:
x[index]
except Exception as e:
e1 = e
else:
>           raise Exception("exception not raised")
E           Exception: exception not raised
sparse/tests/test_core.py:473: Exception
===================================== warnings summary …
> Fix test_slicing_errors failing for older NumPy versions

- setup.py
- tox.ini
Note that the way Travis CI and `py.test` run their tests remain unchanged:
- Travis CI runs multiple Python version tests in seprarate images
- `py.test` works exactly as before
The only difference: Users can run `tox` on their local machines to test Python 2 and 3.
> Tox for cross Python-version testing

- docs/generated/sparse.COO.density.rst
- docs/generated/sparse.COO.rst
- docs/generated/sparse.COO.size.rst
- sparse/core.py
- sparse/tests/test_core.py
NumPy has a `.size` property that gives you the number of elements in an array. 
Additionally for sparse arrays a `.density` property may be handy, which is the ratio of nonzero elements to total elements in the array (a value between `0` and `1`).
This PR implements both properties for `COO` arrays
> Size and density properties

- sparse/coo.py
- sparse/tests/test_coo.py
One approach to the problems described in #72
> Implement __array__ protocol

- docs/operations.rst
- sparse/coo.py
- sparse/tests/test_coo.py
Fixes #95 
Do a little work on `dot` to bring it up to par with `np.dot`.
- Support mixed matrix-vector products (returning a 1-D array).
- Support vector-vector products (returning a scalar).
> Enhance dot + tests.

- docs/generated/sparse.COO.elemwise.rst
- docs/generated/sparse.COO.rst
- docs/generated/sparse.elemwise.rst
- docs/generated/sparse.rst
- docs/operations.rst
- sparse/__init__.py
- sparse/coo.py
- sparse/tests/test_coo.py
- sparse/utils.py
This PR adds N-ary broadcasting operations (in preparation for `where`) and simplifies code for the N-ary case.
Discussed in https://github.com/pydata/sparse/issues/1
> Add N-ary broadcasting operations.

- sparse/coo.py
- sparse/tests/test_coo.py
> Fix negative axes reductions.

- benchmarks/benchmark_coo.py
- docs/generated/sparse.COO.rst
- docs/generated/sparse.COO.sort_indices.rst
- docs/generated/sparse.COO.sum_duplicates.rst
- docs/quickstart.rst
- sparse/coo/common.py
- sparse/coo/core.py
- sparse/coo/indexing.py
- sparse/coo/umath.py
- sparse/dok.py
- sparse/tests/test_coo.py
- sparse/utils.py
Based on recommendations in https://github.com/scipy/scipy/issues/8162#issuecomment-344469036 I believe that we should make `COO` always be canonical.
This has several advantages:
- Nobody really wants the non-canonical version.
- We don't have to keep track of when or if it's ever canonical.
- The `x.sum_duplicates()` calls just disappear.
- The string representation becomes simpler. The `sorted=?, duplicates=?` was just confusing to someone who didn't know how `COO` really worked.
- The object is now truly immutable.
> Make COO canonical in the constructor.

- docs/generated/sparse.COO.nonzero.rst
- docs/generated/sparse.COO.rst
- sparse/coo/core.py
- sparse/tests/test_coo.py
> Add COO.nonzero method.

- .codecov.yml
- .coveragerc
- docs/operations.rst
- sparse/coo/core.py
- sparse/coo/umath.py
- sparse/tests/test_coo.py
Closes #80 
Leverages the existing `__array_ufunc__` implementation without needing too much extra code.
> Inplace ops

- sparse/coo/common.py
- sparse/coo/core.py
- sparse/coo/indexing.py
- sparse/coo/umath.py
- sparse/tests/test_coo.py
- sparse/utils.py
There was a range of bugs relating to small `coords` dtypes (used to save memory) often causing overflows and other bugs, also in interaction with `dask.array`
I removed all `np.min_scalar_type` instances as well as custom small `coords` instances.
This led to a few other bugs, which were also fixed. First seen in https://github.com/scipy-conference/scipy_proceedings/pull/388#discussion_r194598625
Example from that here: https://gist.github.com/hameerabbasi/0230eb7b6359416d1db4167f802ada83
> A range of fixes relating to small coords dtypes

- sparse/coo/indexing.py
- sparse/coo/umath.py
This helps when parallelizing around sparse
> Compile numba code with nogil=True

- docs/generated/sparse.roll.rst
- docs/generated/sparse.rst
- sparse/coo/__init__.py
- sparse/coo/common.py
- sparse/tests/test_coo.py
This is my attempt to implement the equivalent of [`numpy.roll`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.roll.html) which I think would be really useful to have in this package.
I think this is nearly done, but it could be improved. In particular, the function is supposed to produce a copy of the array but I wasn't sure the preferred way of doing that so I called the `COO` constructor directly. Also, my function assumes a COO array as input, which is maybe not so flexible as other sparse array types are developed?
Thanks again for providing this awesome package. Looking forward to your comments!
> Implement roll (circular shift of elements)

- docs/construct.rst
- docs/operations.rst
- docs/quickstart.rst
- sparse/coo/common.py
- sparse/coo/core.py
- sparse/coo/indexing.py
- sparse/coo/umath.py
- sparse/dok.py
- sparse/io.py
- sparse/sparse_array.py
- sparse/tests/test_coo.py
- sparse/utils.py
Closes #143 
Initial implementation for arbitrary fill values.
> Initial implementation for arbitrary fill values.

- sparse/coo/core.py
- sparse/tests/test_coo.py
During initialization, I kept on running into an assert. This PR resolves that and provides a better error message.
Why is `coords` in the shape it is? I would expect `coords.T` to be passed to `__init__`. That is, instead of `coords.shape == (ndim, num_points)`, I would expect `coords.shape == (num_points, ndim)`.
> MAINT: better error messages for initialization

- docs/generated/sparse.COO.all.rst
- docs/generated/sparse.COO.any.rst
- docs/generated/sparse.COO.rst
- sparse/coo/core.py
- sparse/tests/test_coo.py
This PR closes #173 and adds `any` and `all` methods to `COO`.
> ENH: implement any and all functions

- docs/changelog.rst
- sparse/coo/core.py
- sparse/sparse_array.py
- sparse/tests/test_coo.py
Allows specifying a fill-value when converting from a NumPy array.
> Allow fill-value on conversion from NumPy.

- docs/changelog.rst
- docs/operations.rst
- sparse/coo/core.py
- sparse/coo/umath.py
- sparse/tests/test_coo.py
- sparse/utils.py
> Add support for mixed ndarray-sparse element-wise operations.

- sparse/coo/core.py
- sparse/tests/test_coo.py
This is the error that this pull request fixes
```
>>> A = sparse.random((10, 10), density=0.1)
>>> A
<COO: shape=(10, 10), dtype=float64, nnz=10, fill_value=0.0>
>>> B = 1-A
>>> B
<COO: shape=(10, 10), dtype=float64, nnz=10, fill_value=1.0>
>>> B.prod(axis=0)
<COO: shape=(10,), dtype=float64, nnz=8, fill_value=0.0>
```
The `fill_value` should remain `fill_value=1.0` for the object to remain correct.
> tweaked reduce method to return COO with correct fill_value

- docs/changelog.rst
- docs/generated/sparse.eye.rst
- docs/generated/sparse.ones.rst
- docs/generated/sparse.ones_like.rst
- docs/generated/sparse.rst
- docs/generated/sparse.zeros.rst
- docs/generated/sparse.zeros_like.rst
- sparse/coo/__init__.py
- sparse/coo/common.py
- sparse/tests/test_coo.py
Add implementations of `eye`, `zeros`, and `zeros_like`, mirroring the equivalent numpy api.
> Add eye, zeros, zeros_like, ones, ones_like

- docs/changelog.rst
- docs/generated/sparse.COO.copy.rst
- docs/generated/sparse.COO.rst
- sparse/coo/core.py
- sparse/tests/test_coo.py
- Fixes pickle of `COO` to exclude the `_cache` attribute
- Adds a `COO.copy` method to mirror numpy.
> Fixup pickle, add copy

- docs/changelog.rst
- docs/conf.py
- setup.py
Formatting changelog manually gives us more control over the output.
Also cleaned up formatting and links to old PRs to more accurately reflect their PR/issue nature.
Fixes #187.
> Remove `releases` sphinx extension

- docs/changelog.rst
- docs/generated/sparse.full.rst
- docs/generated/sparse.full_like.rst
- docs/generated/sparse.rst
- sparse/coo/__init__.py
- sparse/coo/common.py
- sparse/tests/test_coo.py
Add `sparse.full` and `sparse.full_like`, matching the numpy api.
> Add full and full_like

- docs/changelog.rst
- docs/generated/sparse.COO.mean.rst
- docs/generated/sparse.COO.rst
- docs/generated/sparse.nanmean.rst
- docs/generated/sparse.rst
- sparse/coo/__init__.py
- sparse/coo/common.py
- sparse/coo/core.py
- sparse/tests/test_coo.py
Adds `COO.mean` and `sparse.nanmean`, matching the numpy api
Also applies several cleanups to the reductions test suite:
- Test with larger arrays on numeric reductions. Some issues with current functions only showed up on larger arrays (before there was a decent chance only one element along an axis was nonzero).
- Test with more input dtypes
- XFail tests setting `dtype=float16`. These fail for some, but not all configurations. It's not clear how numpy interprets this for various reductions - neither casting prior to summing or casting after the sum give the same result as numpy depending on configuration. Since `COO.sum` was already failing on larger arrays, I xfailed these tests for now.
- Cleanup superfluous warnings, reducing pytest output
- A few assorted cleanups.
> Add COO.mean and sparse.nanmean

- docs/changelog.rst
- sparse/coo/core.py
- sparse/tests/test_coo.py
Adds support for `np.reshape` to dispatch to `COO.reshape` properly.
> Add order parameter to `COO.reshape`

- .gitignore
- docs/changelog.rst
- sparse/coo/common.py
- sparse/tests/test_coo.py
Generalizes `kron` to an arbitrary number of dimensions.
> Generalise kron to an arbitrary number of dimensions.

- sparse/compatibility.py
- sparse/coo/common.py
- sparse/coo/core.py
- sparse/sparse_array.py
> Fix overflow in reduce.

- docs/operations.rst
- sparse/__init__.py
- sparse/coo/core.py
- sparse/tests/test_coo.py
Add an environment variable to allow configuration of densification.
> Configure densification.

- sparse/coo/common.py
- sparse/tests/test_coo.py
When the first input is 2-D, #204 does not give the correct shape. This PR will Fix #202 in this case.
> Fix wrong shape of matmul result when the first input is 2-D

- docs/generated/sparse.SparseArray.rst
- docs/generated/sparse.SparseArray.todense.rst
- sparse/__init__.py
- sparse/coo/common.py
- sparse/coo/core.py
- sparse/sparse_array.py
- sparse/tests/test_coo.py
> Disallow auto-densification.

- sparse/coo/common.py
- sparse/coo/core.py
- sparse/slicing.py
- sparse/sparse_array.py
- sparse/utils.py
Currently, when using Python 3.7, one sees the following warning when importing `sparse`:
.../sparse/sparse/coo/core.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Iterable, Iterator, Sized
This warning will become an error in Python 3.8, the upcoming version. So it's time to fix it.
> Fix collections-related DeprecationWarnings on import

- sparse/coo/umath.py
Fixes #231 
Fixes #230 
@asmeurer Please make sure that these error messages are clear to you... I'm used to speaking deep NumPy-speak, and so I may be a bit blinded. 🙂
> Clarify error messages

- .gitignore
- docs/generated/sparse.COO.resize.rst
- docs/generated/sparse.COO.rst
- sparse/coo/core.py
- sparse/tests/test_coo.py
I added a validation check in the reshape method for compatibility with numpy. I also added an in-place resize method. I didn't do anything with the refcheck parameter. Just like numpy, the shape can be passed either as a tuple or a series of integers, hence the *args. 
Fixes #241 
Fixes #250
> Add resize method and change reshape

- sparse/coo/common.py
- tests/test_coo.py
> Fix empty tensordot.

- sparse/coo/__init__.py
- sparse/coo/core.py
Hello!
I'm working on a SciPy sprint to get `sparse` arrays into `xarray`.
With a couple tweaks to xarray anticipating objects implementing `__array_function__`, I can get it to work with the following:
* Make `COO.astype()` provide the [copy](https://github.com/pydata/xarray/blob/23fc0d6f8a5affefb84e5f20dc0bef7ace4542e2/xarray/core/duck_array_ops.py#L135) argument
* Expose [result_type()](https://github.com/pydata/xarray/blob/24d49fcd723f20b09998c302dc6003b8de69e595/xarray/core/dtypes.py#L146) though `sparse` to bypass numpy's dispatcher -- I'm importing the lower level function.
(I'm using numpy 1.16 with `'NUMPY_EXPERIMENTAL_ARRAY_FUNCTION'` = `'1'`
Numpy 1.17.0rc1 currently fails due to an issue with numba https://github.com/numba/numba/issues/4319)
> Modifications to enable sparse xarrays

- sparse/sparse_array.py
Fix bug where any of the top-level functions invoked by ``COO.__array_function__`` raises AttributeError for any reason, but the exception is improperly suppressed and ``__array_function__`` returns NotImplemented instead.
> __array_function__ suppresses AttributeError

- sparse/coo/__init__.py
> Remove redundant import.

- sparse/coo/core.py
- sparse/sparse_array.py
- tests/test_array_function.py
> Route gufuncs through __array_function__.

- sparse/coo/umath.py
- tests/test_coo.py
> Allow mixed ndarray-sparse ops where the shape doesn't change.

- docs/generated/sparse.result_type.rst
- docs/generated/sparse.rst
- requirements.txt
- sparse/__init__.py
- sparse/coo/__init__.py
- sparse/coo/common.py
- sparse/coo/core.py
- sparse/settings.py
- sparse/sparse_array.py
- tests/test_array_function.py
- tests/test_coo.py
- Support for numpy 1.17 (it's already what's used in CI today)
- Implement sparse.result_type + unit tests
- Refactor environment variables and other switches into sparse.settings
- Add unit tests for mixed numpy+sparse inputs to ``__array_function__``, with different permutations
> __array_function__ test coverage; numpy 1.17; result_type()

- sparse/_coo/core.py
Coords is not modified anywhere in this class, so we probably do not need to copy it.
This also would allow for identity short-cuts when performing operations on sparse arrays with the same sparsity pattern.
> Avoid making a copy of `coords`

- sparse/_sparse_array.py
- sparse/tests/test_array_function.py
> Fix attribute access for __array_function__.

- setup.py
- sparse/_coo/numba_extension.py
- sparse/_numba_extension.py
- sparse/tests/test_coo_numba.py
Over in pygae/clifford, we're finding we want to be able to write optimized loops using `arr.coords` and `arr.data`.
This aims to be the minimum amount needed to make that work.
~~Marking as draft since this has no tests~~
cc @stuartarchibald, @luk-f-a
> ENH: Add numba extension support for COO objects

- sparse/_sparse_array.py
- sparse/tests/test_coo.py
Includes test that exercises the bug. Illustration:
```
In [1]: import numpy                                                                                                                                                                          
In [2]: import sparse                                                                                                                                                                         
In [3]: a = numpy.zeros((5, 5))                                                                                                                                                               
In [4]: b = sparse.COO(data=[1, 1], coords=(2, 4), shape=(5,)) …
```
> Fix setting into numpy slice

- requirements/tests.txt
- sparse/_coo/core.py
- sparse/tests/test_dask_interop.py
Closes #300
Credit to @crusaderky for suggesting this implementation in that issue.
Here, I add a test. I have verified that it fails as expected before the change
in 136bc85 is introduced.
> Implement deterministic dask tokenization.

- sparse/_common.py
- sparse/tests/test_coo.py
This is modeled on ``cupy.asarray``. Future work may use numpy protocols
to let duck arrays of sparse arrays pass through properly, such as a
dask array of sparse arrays. See #319 and issues linked therein for
discussion. Closes #319
> Implement asarray.

- sparse/_coo/core.py
Previously this would make a copy anyway.
> Respect `copy=False` in `astype`

- sparse/_coo/common.py
```
In [42]: %timeit np.ravel_multi_index(o.coords, o.shape)
11.2 µs ± 1.32 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [43]: %timeit sparse._coo.common.linear_loc(o.coords, o.shape)
35.2 µs ± 2.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
> Replace linear_loc with ravel_multi_index, which is 3x faster

- sparse/_coo/numba_extension.py
Rather than using `contextlib.ExitStack` to manage our state, this uses LLVM basic blocks instead.
cc @stuartarchibald
---
Unfortunately this didn't appear to improve compile-time performance.
> Try to simplify the numba extension a little

- docs/generated/sparse.COO.rst
- sparse/_coo/core.py
- sparse/tests/test_coo.py
Hello,
I wanted to run some code I wrote for numpy arrays with COO arrays from this library, but unfortunately the np.swapaxes method was used. As this method did not exist for sparse arrays I quickly added it to the COO class. I also added a quick test to make sure everything works.
Best regards,
Marvin
> added method swapaxes to COO

- benchmarks/benchmark_coo.py
- benchmarks/benchmark_tensordot.py
- sparse/_coo/common.py
- sparse/tests/test_coo.py
Enhancement of sparse.tenserdot: choose return type. See #348.
The goal is to let the user decide of which type the output of tensordot is. The options are returntype="sparse", "dense" or "auto" (sparse if both arguments are sparse, otherwise dense).
To date only works for returntype="sparse" in the case that the first array is dense and the second array is sparse. The other cases will be implemented in the future.
I am very thankful for suggestions for improvement, especially concerning perfomance.
> Choose sparse/dense type when doing tensordot

- sparse/_coo/core.py
- sparse/tests/test_coo.py
> Fix ND being accepted as COO data.

- sparse/_common.py
- sparse/_compressed/compressed.py
- sparse/_coo/umath.py
- sparse/tests/test_array_function.py
- sparse/tests/test_dot.py
> Fix a number of random bugs.

- sparse/_utils.py
- sparse/tests/test_coo.py
Currently, `sparse.random` uses the `density` argument to determine
the number of non-zero elements in the generated array. If the exact
number of non-zero elements is required, one might try to compute
density as `nnz / np.prod(shape)`, which might give a wrong result
for large values due to a floating-point error.
This PR adds a new, optional `nnz` argument to `sparse.random` that,
if specified, overrides `density` and allows a caller to create
a random array with the exact number of non-zero elements.
> Add nnz parameter to sparse.random

- benchmarks/benchmark_gcxs.py
Here I've added asv benchmarks for GCXS. I also made a couple of changes to COO.
> add benchmarks

- sparse/_coo/numba_extension.py
The suggested `self.self.coords_dtype` did not work for the construction of types.UniTuple():
```
[   73s] >       return self.data[ref(key)]
[   73s] E       TypeError: Failed in nopython mode pipeline (step: nopython mode backend)
[   73s] E       cannot create weak reference to 'numpy.dtype' object
```
But using numba's correct integer type for pointers works.
Fixes #420
> use correct pointer type for coo shape

- sparse/_dok.py
- sparse/tests/test_dok.py
Modify `__setitem__` to support a subset of advanced/fancy indexing where all dimensions are indexed. This uses @stschroe's gist [here](https://gist.github.com/stschroe/7c4660774835258c06b2be968eb49204#file-sparse_dok_indexer-py).
We also need `__getitem__`, but we thought we'd submit that as a separate PR.
> Add fancy indexing support for DOK item assignment

- sparse/_dok.py
- sparse/tests/test_dok.py
Extend DOK `__getitem__` to support slicing and fancy indexing when all dimensions are indexed.
> Add slicing and subset of fancy indexing to DOK array access

- sparse/_dok.py
- sparse/_umath.py
- sparse/tests/test_dok.py
- sparse/tests/test_elemwise.py
Behaves as closely as possible to `np.ndarray` comparisons
- Single values are broadcast
- Broadcasting for arrays of different shapes is as per `numpy` broadcasting rules
- Always returns a new DOK array of bools
@hameerabbasi I think this is the last operation we need for our use-case over at napari. Please let me know if there's any changes you'd like made!
> Implement equality comparison for DOK arrays

- sparse/_compressed/common.py
- sparse/_compressed/compressed.py
- sparse/_compressed/convert.py
- sparse/_compressed/indexing.py
- sparse/_coo/common.py
- sparse/_coo/core.py
- sparse/_utils.py
- sparse/tests/test_compressed.py
- sparse/tests/test_coo.py
In this version, I've added a `storage_dtype` argument in the `COO` and `GCXS` constructors. For most operations, the result array will use the same storage dtype as the input array. There are a few places where the output is upcast to a larger dtype if the input dtype is too small. I decided to do this because in these situations no error is raised and the output is simply wrong. Where it doesn't make sense to upcast, I have it raise an error.
> allow for use of different dtypes in coords, indices, and indptr

- sparse/_compressed/compressed.py
The `GCXS` docstring now has some information on the structure and advantages of GCRS/GCCS scheme.
> Modify GCXS docstring

- docs/construct.rst
@hameerabbasi I've updated the docs to include elementwise operations for DOK arrays. 
At this point I'm not sure whether you want to keep the DOK documentation in Construct Sparse Arrays, or whether you'd like to pull it out as its own section, but please let me know if that's the case, and whether you want more detail on the elementwise operations e.g. more detail on comparisons, etc. As it is, I tried to follow the convention already used for the COO arrays.
> Document elementwise functions for DOK arrays

- sparse/_sparse_array.py
In the docstring of the `var` function, it says "gi66ven" instead of "given". I assume that this is a typo?
I created a pull request but maybe you would have preferred that I opened an issue instead.
> Fix typo in var function docstring

- docs/index.rst
- docs/operations.rst
- docs/roadmap.rst
Adds GCXS to operations.rst and adds GCXS and CSR/CSC to the completed tasks section of the roadmap.
> Update docs for GCXS and CSR/CSC

- sparse/_common.py
- sparse/_compressed/compressed.py
- sparse/_coo/common.py
- sparse/_coo/core.py
- sparse/_dok.py
- sparse/_io.py
- sparse/_slicing.py
- sparse/_sparse_array.py
- sparse/_umath.py
- sparse/_utils.py
This uses an automatic reformatter to fix some of the common mistakes.
A few manual were needed, for example Numpydoc really want section to be separated by empty lines, or it start to say that `Return`, `------` are parameter of a function.
Spaces around colons or not in parameters have a different semantic meaning when parsing – it may not show in sphinx html, but internally the data is different and is messed up for crosslinks.
This also fixed a couple of parameter names typos (x/a or coord/shape/ndim inversion ...)
> Attempt to reformat docstring to match Numpydoc standard.

- sparse/_compressed/indexing.py
- sparse/_umath.py
- sparse/tests/test_coo.py
- sparse/tests/test_dok.py
> Maintance fixes.

- sparse/_common.py
- sparse/tests/test_dot.py
Fixes #340 with a warning for now.
> Added warnings for NaN propagation

- sparse/_dok.py
- sparse/tests/test_coo_numba.py
This is super minor, but I noticed when I forked the repository (just to look at things), a couple of tests fail when you run `pytest --pyargs sparse` as described in the [contributing guide](https://github.com/pydata/sparse/blob/master/docs/contributing.rst).
The reason for the two test failures is some whitespace that the black formatting tool doesn't like. So it's nothing important, but it's always nice to have things work smoothly when new people go through the contributing guide.
> Pytest failures - fixed with black re-formatting

- sparse/tests/conftest.py
Disable doctest on 32bits architectures because they generate innocent errors.
See https://github.com/pydata/sparse/issues/428#issuecomment-771893752 and https://bugs.debian.org/988424
Now, during a build on a 32bits system, we have other errors:
```
=================================== FAILURES ===================================
___________________________ TestBasic.test_roundtrip ___________________________
self = <test_coo_numba.TestBasic object at 0xed466400>
def test_roundtrip(self):
c1 = sparse.COO(np.eye(3), fill_value=1)
>       c2 = identity(c1)
tests/test_coo_numba.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3/dist-packages/numba/core/dispatcher.py:414: in _compile_for_args
error_rewrite(e, 'typing')
_ _ _ _ _ _ _ _ _ _ …
```
> Skip doctest on 32bits arch

- docs/conf.py
Links in documentation pointing to the scipy API docs are currently broken. This fixes issue #542 to point to the correct scipy API urls
> fix scipy url in intersphinx mapping

- sparse/_common.py
- sparse/_compressed/compressed.py
- sparse/_coo/core.py
- sparse/_coo/numba_extension.py
- sparse/_dok.py
- sparse/_numba_extension.py
Use relative imports, apart from being a good code style it makes vendoring sparse within another package easier.
> Relative imports (helps vendoring)

- sparse/_compressed/convert.py
- sparse/tests/test_compressed_convert.py
Possibly closes #550. Needs some review as I did not fully grok what `compute_flat` was doing here, but it seemed like it was failing to account for multi-dimensional sparse arrays properly.
There might be a better way to do this (or a better way to calculate this more generally, I'm not sure) but this seems to have fixed the problem identified in #550 as well as some crashes I observed in particularly bad situations.
> fix errors/crashes in multi-dimensional slicing

- sparse/_compressed/convert.py
- sparse/_compressed/indexing.py
- sparse/tests/test_compressed_convert.py
While working on #569*, I realized that there were a few optimizations that could be performed, and with a little additional work I could use `numba.jit` on `_compressed.convert.convert_to_flat` as well.
\* that PR should be merged first, as this builds on it
Short summary of changes:
* removed an array allocation and let numba optimize a loop in `compute_flat`, which was roughly half the time in that function.
* similarly, removed an array allocation and the use of `np.prod` and let numba take care of it
* part of the work of building `cols` can be performed up front with the equivalent of `np.tile` (but that's not a numba-compatible function so this is the equivalent). This required changing my tests a little.
* simplified `transform_shape` a little bit--no reason to iterate backwards
* …
> Improving indexing performance

- sparse/_compressed/compressed.py
- sparse/_coo/core.py
- sparse/_dok.py
- sparse/_sparse_array.py
- sparse/tests/test_array_function.py
Currently, only 'dok' supports `.format`:
```python
import sparse
for format in ["dok", "gcxs", "coo"]:
s = sparse.random((5, 5), density=0.2, format=format)
print(s.format)
```
> Add .format support to GCXS and COO classes

- sparse/_common.py
- sparse/tests/test_einsum.py
After testing the implemented einsum (many thanks for implementing), it turns out that the ellipsis were not working (and they are used by xarray dot function, my primary motivation for making this work). So in this commit there is an added function _parse_einsum input that is borrowed from numpy with the only change that operand are not cast to numpy array but are left untouched.
> change parsing of the input in einsum

- sparse/_sparse_array.py
I noticed that `SparseArray.var` can potentially try to call `warnings.warn` ([here](https://github.com/pydata/sparse/blob/master/sparse/_sparse_array.py#L767)) but it was never imported.
> Minor bug: import warnings in `_sparse_array.SparseArray`

- sparse/_compressed/compressed.py
- sparse/_coo/core.py
- sparse/_dok.py
- sparse/_sparse_array.py
If available, use the [matrepr](https://github.com/alugowski/matrepr) package to render array values in string and HTML output.
Reverts to current behavior if matrepr is not installed.
See this [Jupyter notebook](https://nbviewer.org/github/alugowski/matrepr/blob/main/doc/demo-pydata-sparse.ipynb) for a demo of what 1D, 2D, and 3D sparse arrays look like when rendered by matrepr.
Closes #604
> Use matrepr for rich `__str__` and `_repr_html_`

- sparse/_umath.py
- sparse/_utils.py
- sparse/tests/test_coo.py
`np.array("").dtype.type[...]` doesn't work to create an array. 
* Use np.asarray to create the fill value array instead.
* Fix assert_eq so it uses np.array_equal for strings.
Closes #608
References
https://numpy.org/doc/stable/reference/arrays.scalars.html#indexing
> Fix issue with .real/.imag with string dtypes

- sparse/_coo/common.py
- sparse/tests/test_coo.py
This PR refactors the current implementation of `argmax` and `argmin`. It removes "only 0.0 fill value" and "all non-fill values greater/less than the fill value" constraints. It also makes the core of the function jittable. 
First https://github.com/pydata/sparse/pull/613 needs to be merged.
> API: Refactor `argmax` and `argmin`

- sparse/__init__.py
- sparse/_common.py
- sparse/_coo/common.py
- sparse/_sparse_array.py
- sparse/_umath.py
- sparse/tests/test_array_function.py
- sparse/tests/test_coo.py
- sparse/tests/test_elemwise.py
This PR refines `sparse.asarray` by including original `dtype` of the passed array.
It also adds `__array_namespace__`, `__array_api_version__` (Array API compatibility), and some minor improvements.
> API: Improve `sparse.asarray`

- sparse/_umath.py
This PR closes #596 in a fairly simple way: if all of the inputs are GCXS arrays and they have the same compression, it will return the output with the same compression. I just do this by storing a `kwargs` dictionary during the `_Elemwise` initialization.
A further enhancement that I'm exploring: if the `ufunc` has a single input, we could avoid the conversion to `COO` entirely, as well as skip some other checks. In this case we know that our argument is sparse (or we wouldn't be creating this class) and we know that it "broadcasts" to the same shape. The things to consider are the potential keywords for the ufunc: `where`, `out`, etc.
> Preserve gcxs compression

- docs/construct.rst
- pyproject.toml
Reran the examples in [Construct Sparse Arrays](https://sparse.pydata.org/en/stable/construct.html) with `matrepr` installed to show the result of each snippet.
Previously only the first example showed the result, but only as a dense array. This change illustrates the sparsity of the sparse arrays. Some examples become easier to follow, such as the last example showing a "bad" identity matrix with explicit zeros and a fill value of 1. A visualization of the array reinforces the written description.
> DOC: Add array representations to sparse array construction examples

- sparse/__init__.py
- sparse/_coo/__init__.py
- sparse/_coo/common.py
- sparse/tests/test_coo.py
This PR adds four set functions for COO format described in the [Array API standard](https://data-apis.org/array-api/latest/API_specification/set_functions.html):
- ~~`unique_all`~~
- `unique_counts`
- ~~`unique_inverse`~~
- `unique_values`
> API: Add set functions [Array API]

- sparse/_common.py
- sparse/tests/test_einsum.py
Related issue: #589
I think the original error was caused due to the fact that `np.einsum` has kwargs which is missing in `sparse.einsum`. There is no Array API standard definition for `einsum` function so maybe we can just add `**kwargs` to `sparse.einsum` to make it compatible.
If there are plans for refactoring `sparse.einsum` in the future, then there will be an opportunity to introduce `dtype` parameter.
> API: Add `kwargs` to `sparse.einsum`

- .pre-commit-config.yaml
- benchmarks/benchmark_coo.py
- benchmarks/benchmark_gcxs.py
- benchmarks/benchmark_matmul.py
- benchmarks/benchmark_tensordot.py
- pyproject.toml
- sparse/_common.py
- sparse/_compressed/compressed.py
- sparse/_compressed/convert.py
- sparse/_compressed/indexing.py
- sparse/_coo/common.py
- sparse/_coo/core.py
- sparse/_coo/indexing.py
- sparse/_dok.py
- sparse/_io.py
- sparse/_settings.py
- sparse/_slicing.py
- sparse/_sparse_array.py
- sparse/_umath.py
- sparse/_utils.py
- sparse/tests/conftest.py
- sparse/tests/test_compressed.py
- sparse/tests/test_compressed_2d.py
- sparse/tests/test_compressed_convert.py
- sparse/tests/test_coo.py
- sparse/tests/test_dok.py
- sparse/tests/test_dot.py
- sparse/tests/test_einsum.py
- sparse/tests/test_elemwise.py
This PR also adds lints that check for NumPy 2.0 compatibility.
> Add more lints to Ruff for better code quality.

- sparse/_compressed/indexing.py
- sparse/_umath.py
- sparse/_utils.py
> Always use `np.intp` for indices.

- .github/workflows/ci.yml
- pyproject.toml
- sparse/_coo/common.py
This PR introduces CI changes that we did in `finch-tensor`.
> CI: Remove Python 3.8 and update miniconda

- benchmarks/benchmark_gcxs.py
- sparse/_common.py
Improves the memory access pattern for `GCXS` arrays dot `ndarray`s.
Was running a few benchmarks of the GCXS class against scipy's csr/csc arrays and noticed that they were significantly slower. So was curious what the biggest difference was as their structures shouldn't be too fundamentally different. When looking at the csr_dot_ndarray code and the csc_dot_ndarray code I realized that the access pattern of the arrays was inefficient.
Here are some of the relevant timings of things:
```python
import scipy.sparse as sp
import sparse
import numpy as np
```
```python
state = np.random.default_rng(seed=1337)
A_gc0s = sparse.random((9000, 10000), format='gcxs', random_state=state).change_compressed_axes((0,))
A_gc1s = A_gc0s.change_compressed_axes((1,))
A_csr = A_gc0s.to_scipy_sparse()
A_csc …
```
> Improve performance of GCXS dot ndarray

- .github/workflows/ci.yml
- ci/environment.yml
- pyproject.toml
- sparse/__init__.py
- sparse/finch_backend/__init__.py
- sparse/tests/test_backends.py
Initial `finch_backend` setup.
> API: Initial `finch_backend`

- sparse/finch_backend/__init__.py
- sparse/tests/test_backends.py
This small PR updates Finch backend with what we currently have in the latest `finch-tensor` release.
> Update Finch backend

- pyproject.toml
- sparse/finch_backend/__init__.py
- sparse/tests/test_backends.py
Once https://github.com/willow-ahrens/finch-tensor/pull/31 is merged this PR will make sure that `scipy.sparse` also accepts finch-backend tensors!
> API: Enable finch backend for `scipy.sparse`

- .coveragerc
- .github/workflows/ci.yml
- ci/array-api-skips.txt
@mtsokol This will do what I suggested in https://github.com/pydata/sparse/pull/668#issuecomment-2079356755, in that we're required to remove tests that pass from the skips file. This will ensure that we don't regress and remember to update the file as well.
> Do strict checking of Array API in CI job.

- .github/workflows/ci.yml
- benchmarks/benchmark_backends.py
- ci/test_examples.sh
- examples/sddmm_example.py
- pyproject.toml
This PR adds `SDDMM` example and upgrades Finch to the latest version.
**[UPDATED 14.05.2024]**
For my machine, running:
```bash
python examples/sddmm_example.py
```
gives:
```
Finch
Took 8.787564675013224 s.
Numba
Took 22.904020706812542 s.
SciPy
Took 22.59452811876933 s.
```
> Add `SDDMM` example

- examples/mttkrp_example.py
- examples/sddmm_example.py
Hi @willow-ahrens @hameerabbasi,
This PR adds the second example: MTTKRP (I followed http://tensor-compiler.org/docs/data_analytics.html formula).
On my machine the current setup (tensors' dimensions and density) Finch shows x6 speedup compared to Numba.
> Add `MTTKRP` example

- ci/array-api-skips.txt
- ci/array-api-xfails.txt
- sparse/tests/conftest.py
- sparse/tests/test_backends.py
Here's a PR that contains:
- Moved `test_unary[sign((x_i is -0 or x_i == +0)) -> 0]` to skips as this test is now flaky (it correctly failed in the PR but I see in the main branch it succeeded causing XPASS, so I guess `--derandomize` didn't get rid of all randomness)
- `test_scipy_sparse_csgraph_dispatch` with `scipy.sparse.csgraph` tests
- commented out a few linalg tests that require https://github.com/scipy/scipy/pull/20759 (and a new scipy release)
- `test_scikit_learn_dispatch`, skipped for now as it requires https://github.com/scikit-learn/scikit-learn/pull/29031
> Add tests for `scipy.sparse.csgraph` and `scipy.sparse.linalg`

- sparse/numba_backend/_compressed/compressed.py
- sparse/numba_backend/_coo/core.py
- sparse/numba_backend/_dok.py
- sparse/numba_backend/_utils.py
- sparse/numba_backend/tests/test_compressed.py
- sparse/numba_backend/tests/test_coo.py
This pull request adds functionality to convert from/to SciPy sparse matrices, while supporting non-zero fill-values.
> `scipy.sparse` fill-value fix.

- examples/matmul_example.py
This is the last example from your list that I wanted to add (for `solve` we dispatch to `scipy.sparse`):
```
matmul = lambda x, y: np.sum(x[:, None, :] * y.transpose((1, 0))[None, None, :], axis=2)
spmv = lambda x, y: np.sum(x * y[:, None], axis=1)
tensordot  # various axes
sddmm = lambda s, x, y: s.astype(bool) * (x @ y)
mttkrp = lambda b, c, d: sum(b[:, None, :, :] * d.transpose((1, 0))[None, :, None, :] * c.transpose((1, 0))[None, :, :, None], axis=(2, 3))
solve
```
> Add `matmul` example

- ci/Numba-array-api-xfails.txt
- sparse/numba_backend/_coo/common.py
This PR fixes `argmin`/`argmax` when input is 1D and result is a fill value. To reproduce:
```python
sparse.argmax(sparse.asarray(np.arange(1), dtype=np.uint8)).dtype  # defaulted to `float64` as `np.array([]).dtype` is `float64`. Now it's `intp`
```
> Fix 1D return dtype in argmax/argmin

- ci/test_examples.sh
- ci/test_notebooks.sh
- examples/elemwise_example.py
- examples/matmul_example.py
- examples/mttkrp_example.py
- examples/sddmm_example.py
- examples/spmv_add_example.py
- examples/utils.py
This PR adds CI mode to examples reducing `examples` job execution time (each benchmark returns after precompilation stage).
> MNT: Add CI mode to examples

- docs/index.md
This one was sending to the middle of the page.
> docs: Fix how-to guides link on card

- docs/contributing.md
- mkdocs.yml
- sparse/numba_backend/_common.py
- Closes #
***
- Took docstring from API array, but did some changes. Please tell me if this is OK.
- Modified table of content to 3, to show the functions and attributes to the right of the screen. (With 2, there is no way to find the members of a class other than scroll down).
> docs: Added `sparse.max` docstring

- benchmarks/test_benchmark_coo.py
- Closes #
***
This is @hameerabbasi code (shared on slack).
> test: Benchmark to be run on codspeed

- benchmarks/conftest.py
- benchmarks/test_benchmark_coo.py
- Closes #
***
Original benchmarks used fixed rank
> test: Modified index and slice tests in order to vary ranks

- examples/sparse_finch.ipynb
- sparse/__init__.py
- sparse/numba_backend/_common.py
- sparse/numba_backend/_coo/core.py
- sparse/numba_backend/_sparse_array.py
- sparse/numba_backend/_utils.py
- sparse/numba_backend/tests/test_coo.py
- sparse/tests/conftest.py
- sparse/tests/test_backends.py
***
This PR cleans up the deprecations introduced previously, and it makes sure no warnings are triggered during the tests.
There is still some Numba code using reflected lists (which are deprecated); that needs to be refactored.
> depr, chore: Enforce deprecations and clean up warnings.

- ci/environment.yml
- sparse/mlir_backend/__init__.py
- sparse/mlir_backend/_constructors.py
- sparse/mlir_backend/_core.py
- sparse/mlir_backend/_ops.py
This PR updates codebase to LLVM `19.1.0.rc3` compatible version.
> bld: Upgrade LLVM version to `19.1.0.rc3`

- sparse/mlir_backend/_constructors.py
- sparse/mlir_backend/_core.py
- sparse/mlir_backend/_ops.py
- sparse/mlir_backend/tests/test_simple.py
This PR refactors MLIR Tensor constructors and removes some boilerplate by introducing: `BaseFormat` that defines interface for implementing Dense variants, COO, CSR (present currently), and allows to implement CSC, CSF, and others in the future.
> MNT: Refactor MLIR constructors

- sparse/mlir_backend/_common.py
- sparse/mlir_backend/_constructors.py
- sparse/mlir_backend/_core.py
- sparse/mlir_backend/_ops.py
- sparse/mlir_backend/tests/test_simple.py
This PR moves MLIR constructors to the direct style (with: `sparse-assembler{direct-out=true}`).
I think it's more concise with this approach - `_constructors.py` LOC reduced by 50%, to 250.
Now all Tensors created from NumPy arrays or SciPy sparse arrays are owned and freed by the python side. 
The ones that are results of MLIR ops (like `add` right now) are allocated by MLIR and `owns_memory` in Tensor class is set to `False`. 
I haven't figured out yet how to correctly free MLIR allocated memrefs, (tried with `libc.free`) as I think there's still a memory leak after `sparse.add(tensor_a, tensor_b)`.
> MNT: Move constructors to a direct style

- sparse/mlir_backend/__init__.py
- sparse/mlir_backend/_constructors.py
- sparse/mlir_backend/_ops.py
- sparse/mlir_backend/tests/test_simple.py
This PR adds support for CSC and CSF formats.
> ENH: CSC and CSF formats for MLIR backend

- sparse/mlir_backend/__init__.py
- sparse/mlir_backend/_constructors.py
- sparse/mlir_backend/_ops.py
- sparse/mlir_backend/tests/test_simple.py
This PR adds Array API [reshape](https://data-apis.org/array-api/latest/API_specification/generated/array_api.reshape.html) function (without `copy` keyword for now).
Unfortunately calling `sparse.reshape(...)` gives a segmentation fault (on exit) - I haven't figured out it yet.
> ENH: Implement `reshape` function

- examples/triangles_example.py
- pyproject.toml
Here's a short example that runs counting triangles with Finch, SciPy, and NetworkX. Two comments:
- The Finch implementation is the slowest right now, it's only run in eager mode as lazy mode is blocked by https://github.com/willow-ahrens/Finch.jl/issues/615
- I see that examples in `examples/` directory aren't executed in the CI job anymore, is it intended? I think they should still be executed.
> ENH: Add counting triangles example

- sparse/mlir_backend/__init__.py
- sparse/mlir_backend/_common.py
- sparse/mlir_backend/_constructors.py
- sparse/mlir_backend/_ops.py
- sparse/mlir_backend/tests/test_simple.py
This PR:
- Enables COO of rank higher than 2.
- Improves `reshape` function so that it allows reshaping with 1-size dimensions across different ranks, e.g. `(8, 1, 2)` into `(8, 2)`.
For `reshaping` across different ranks we need some kind of logic for selecting new sparse format. I implemented the simplest option in `_infer_format_class`, but I guess we can come up with smarter logic.
> ENH: Support 3D COO and cross-rank `reshape`

- sparse/mlir_backend/__init__.py
- sparse/mlir_backend/_ops.py
- sparse/mlir_backend/tests/test_simple.py
This PR adds [`broadcast_to`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.broadcast_to.html) Array API function.
It it only broadcasts missing dimensions, for `1`-size dimension it can't broadcast as it's a limitation of `linalg.broadcast` in MLIR.
> ENH: Implement `broadcast_to` function

- sparse/mlir_backend/_constructors.py
- sparse/mlir_backend/tests/test_simple.py
I started porting [Array API vecdot function](https://data-apis.org/array-api/latest/API_specification/generated/array_api.vecdot.html) to Finch MLIR backend. So far it's 1D only so here's a SparseVector format that is needed for it.
> ENH: Add `sparse_vector` constructor

- pyproject.toml
This should fix https://github.com/finch-tensor/Finch.jl/issues/644
> update finch-tensor-python to fix tests

- sparse/mlir_backend/tests/test_simple.py
- Closes #
***
This PR fixes a Heisenbug introduced by the 3D COO test, which often caused the `sparse_vector` test (which is the next test to be executed) to fail.
The reason for this was that the COO test was sometimes writing to memory it shouldn't be, IMO. Just another case of COO being broken.
> Attempt to fix Heisenbug by skipping COO.

- .github/workflows/ci.yml
This PR reverts CI change introduced in #799.
> BLD: Revert micromamba version to v2

- sparse/mlir_backend/_conversions.py
- sparse/mlir_backend/tests/test_simple.py
As described in https://github.com/llvm/llvm-project/issues/116012#issuecomment-2497561848 this PR re-enables COO tests and makes (temporarily) COO instantiation copy-full.
Addition ops with COO still fail though.
> MAINT: Re-enable COO tests after fix

- sparse/mlir_backend/_conversions.py
- sparse/mlir_backend/_dtypes.py
- sparse/mlir_backend/tests/test_simple.py
- Closes #
***
- Hold reference to converted scipy.sparse.coo_*.
- Allow comparison against NumPy dtypes.
- Add a sentence explaining the sparse_vector failure.
> Allow no-copy construction from SciPy COO arrays.

- pixi.toml
- sparse/mlir_backend/_conversions.py
I tested the latest bugfix releases for SciPy from 1.12 to 1.14; and none of them have this issue. I think it's safe to remove the workaround.
> Remove workaround introduced in #822.

- ci/Finch-array-api-xfails.txt
- sparse/numba_backend/_compressed/compressed.py
- sparse/numba_backend/tests/test_compressed_2d.py
It looks like transposing CSC/CSR drops fill-value. Here's a fix.
> Fix CSC/CSR `.mT` fill-value result

- .pre-commit-config.yaml
- ci/Numba-array-api-xfails.txt
- sparse/numba_backend/_common.py
- sparse/numba_backend/tests/test_coo.py
Trying to fix :
```
test_vecdot - AssertionError: out.dtype=uint64, but should be uint8 [vecdot(uint8, uint8)]
```
while running `array_api_tests`.
> Make `vecdot` compliant to the Array API

- ci/Numba-array-api-xfails.txt
- sparse/numba_backend/_coo/common.py
Removes :
```
FAILED ../array-api-tests/array_api_tests/test_sorting_functions.py::test_sort - AssertionError: out.shape=(), but should be (1,) [sort()]
```
While running array-api-tests.
> Addressing array api failure for sort() function

- sparse/numba_backend/_utils.py
- sparse/numba_backend/tests/test_coo.py
- Closes #869 
***
Fixes an issue with complex dtypes and `loose=True`.
Use loose comparisons for `check_zero_fill_value`.
> fix: Fix for `check_zero_fill_value` and `equivalent`

- ci/Numba-array-api-xfails.txt
- sparse/numba_backend/__init__.py
- sparse/numba_backend/_common.py
- sparse/numba_backend/tests/test_coo.py
- sparse/numba_backend/tests/test_namespace.py
- Closes #
***
Added the suppport for `tile` function (np.tile equivalent).
> Adding `tile` function

- docs/operations.md
- sparse/numba_backend/_settings.py
> Setting `boolean indexing` flag to False

- ci/Numba-array-api-xfails.txt
- sparse/numba_backend/__init__.py
- sparse/numba_backend/_common.py
- sparse/numba_backend/tests/test_coo.py
- sparse/numba_backend/tests/test_namespace.py
***
Adding support for the `unstack` function.
> Adding `unstack` function

- ci/Numba-array-api-xfails.txt
- sparse/numba_backend/__init__.py
- sparse/numba_backend/_common.py
- sparse/numba_backend/tests/test_coo.py
- sparse/numba_backend/tests/test_namespace.py
- Closes #592
***
Added sparse equivalent of `np.diff`
> Adding `diff` function

- benchmarks/conftest.py
- benchmarks/test_benchmark_coo.py
- benchmarks/test_elemwise.py
- benchmarks/test_tensordot.py
- Related issue #889
- Closes #
***
> Making benchmarking tests deterministic

- benchmarks/test_benchmark_coo.py
- benchmarks/test_elemwise.py
> Using pytest fixtures to improve benchmarking tests
