sparse/core.py, sparse/tests/test_core.py
@jakevdp you might be more familiar with this code.  Do you see a cleaner way to support this?  
Also, thoughts on removing non-zeros eagerly?  I can see going either way on this.
=> Support multiplication with empty arrays

sparse/core.py, sparse/tests/test_core.py
I've tested this on Python 3.6.3, with unit tests and flake8.
Some formatting changes occurred because I used PyCharm's reformat file.
=> Added elementwise_binary broadcasting and broadcast_to

sparse/core.py, sparse/tests/test_core.py
Added bitwise operators and made changes so comparisons with zero are robust.
=> Bitwise ops

sparse/core.py, sparse/tests/test_core.py
I've implemented `__array_ufunc__` for the `__call__` and `reduce` methods.
=> Add __array_ufunc__ for __call__ and reduce

sparse/core.py, sparse/tests/test_core.py
Fixes the issue described in https://github.com/dask/dask/pull/2980#issuecomment-354517094
=> Fix error on empty reduction + tests.

requirements.txt
Fixes #65 
Update the minimum version of Scipy in `requirements.txt`
=> Update Scipy version in requirements.txt.

setup.py, sparse/core.py
Fixes #73 
This gets CI tests running again so real project failures can be more properly seen.
=> Fix CI tests.

sparse/core.py
=> Fix large sum.

sparse/dok.py, sparse/tests/test_dok.py
=> Fix set to zero.

setup.py, sparse/coo.py, sparse/tests/test_coo.py
=> Match ufunc.reduce behavior.

.coveragerc, .travis.yml, README.rst, setup.cfg, setup.py, tox.ini
=> Improve CI and packaging

.codecov.yml, .travis.yml, pytest.ini, setup.cfg, setup.py, tox.ini
=> Variety of testing/infrastructure fixes.

sparse/coo/common.py, sparse/coo/core.py, sparse/coo/indexing.py, sparse/tests/test_coo.py, sparse/utils.py
I cleaned up #119 and incorporated my own suggestions into it.
Note: When merging this, add @nils-werner as a [co-author](https://help.github.com/articles/creating-a-commit-with-multiple-authors/).
=> Fix axes normalization bugs

.circleci/config.yml, README.rst, ci/environment-2.7.yml, ci/environment-3.6.yml
Jobs set to run in parallel and cache their respective conda environments.
Resolves #120 
Someone with admin rights will have to enable to circle hooks, and then I can rebase to trigger the job to make sure everything is working.
=> Switch from Travis CI to CircleCI

sparse/coo/umath.py
This PR merges the unnecessary "unary ufunc" case and the "n-ary" ufunc case under a single umbrella, so the unary case is no longer a special case.
=> Unfiy unary and n-ary elemwise

sparse/coo/umath.py
ASV Benchmark:
`master`:
```
[ 55.56%] ··· Running ...hmark_coo.ElemwiseBroadcastingSuite.time_add     4.87ms
[ 61.11%] ··· Running ...hmark_coo.ElemwiseBroadcastingSuite.time_mul     1.05ms
[ 66.67%] ··· Running benchmark_coo.ElemwiseSuite.time_add                8.37ms
[ 77.78%] ··· Running benchmark_coo.ElemwiseSuite.time_mul                2.42ms
```
`HEAD`:
```
[  5.56%] ··· Running ...hmark_coo.ElemwiseBroadcastingSuite.time_add     3.81ms
[ 11.11%] ··· Running ...hmark_coo.ElemwiseBroadcastingSuite.time_mul   672.00μs
[ 16.67%] ··· Running benchmark_coo.ElemwiseSuite.time_add                5.84ms
[ 27.78%] ··· Running benchmark_coo.ElemwiseSuite.time_mul                1.94ms
```
=> Avoid some unnecessary operations in elemwise.

docs/conf.py, setup.cfg, sparse/coo/indexing.py, sparse/coo/umath.py, sparse/tests/test_coo.py
Code is now fully PEP8 compliant!
=> Flake8 fixes.

MANIFEST.in, docs/changelog.rst, docs/conf.py, docs/requirements.txt, setup.py
=> Update changelog and move to the releases package for changelogs.

sparse/coo/core.py, sparse/tests/test_coo.py
=> Fix NumPy matrix bug.

sparse/coo/common.py, sparse/tests/test_coo.py
Add a custom-coded dot product. Done:
=> [WIP] Add a custom-coded dot product.

sparse/coo/core.py, sparse/dok.py, sparse/tests/test_dok.py
=> Fix DOK/COO fill-value interface

sparse/coo/core.py, sparse/utils.py
=> Fix random incorrect intermediate shape.

sparse/coo/core.py, sparse/tests/test_coo.py
=> Support reduce fill_value in specific cases.

.travis.yml, docs/generated/sparse.argwhere.rst, docs/generated/sparse.rst, sparse/coo/__init__.py, sparse/coo/common.py, sparse/coo/core.py, sparse/sparse_array.py, sparse/tests/test_array_function.py
I still need to work on tests.
=> [WIP] Add __array_function__ support.

sparse/coo/umath.py, sparse/tests/test_coo.py
=> Fix 1 size non-empty broadcast.

docs/generated/sparse.isneginf.rst, docs/generated/sparse.isposinf.rst, docs/generated/sparse.rst, sparse/coo/__init__.py, sparse/coo/common.py
=> Add isposinf and isneginf.

sparse/_slicing.py, sparse/tests/test_coo.py
=> Fix indexing for empty lists.

azure-pipelines.yml, setup.py, sparse/_coo/core.py, sparse/_dok.py, sparse/tests/test_dok.py
=> Fix incorrect dtype on empty DOK->COO.

sparse/_coo/common.py, sparse/tests/test_coo.py
=> Add error msg to tensordot operation when ndim==0

.gitignore, azure-pipelines.yml, ci/environment-3.8.yml, docs/conf.py, requirements.txt, setup.py, sparse/_coo/common.py, sparse/_coo/numba_extension.py
=> Prepare for Numba 0.49.

sparse/_common.py, sparse/_coo/core.py, sparse/tests/test_coo.py
=> Fix np.outer and np.ufunc.outer.

sparse/_coo/core.py, sparse/tests/test_coo.py
=> Fix scalar initialization with list inputs.

sparse/_meta/numba_bindings.py
The following now works
```python
@njit
def foo(N, ordered, unique):
d = Dense(N=N, ordered=ordered, unique=unique)
return d
@njit
def bar(d):
print(d.N)
d = foo(3, True, True)
bar(d) # prints 3
```
=> @box and @unbox for dense level

sparse/_common.py, sparse/tests/test_dok.py
=> Fix format kwarg in zeros_like.

pytest.ini, sparse/_coo/core.py, sparse/tests/test_coo.py
=> Add the casting kwarg to astype.

sparse/_common.py, sparse/tests/test_dot.py
=> Fix dot for complex dtypes.

sparse/_compressed/compressed.py
=> Add fill value pruning to GCXS

docs/generated/sparse.rst, sparse/__init__.py, sparse/_compressed/compressed.py, sparse/_compressed/convert.py, sparse/_compressed/indexing.py
- Makes gcxs public api
- adds docs
I think updating index.rst and roadmap.rst is appropriate.
=> Add gcxs to docs

azure-pipelines.yml, requirements.txt, sparse/_common.py, sparse/tests/test_coo.py
=> Add shape= kwarg in {zeros, ones, full}_like.

docs/construct.rst
Document new functionality for DOK array
Should be merged after #436.
=> Document ability to slice and fancy index DOK arrays

sparse/_compressed/compressed.py, sparse/_coo/core.py, sparse/tests/test_compressed.py
=> Make a number of immutability changes.

sparse/_utils.py, sparse/tests/test_coo.py
=> Fix ZeroDivisionError on html_table.

docs/generated/sparse.DOK.from_scipy_sparse.rst, docs/generated/sparse.DOK.rst, sparse/_dok.py, sparse/tests/test_dok.py
=> Add DOK sparse constructor.

sparse/_common.py, sparse/_compressed/compressed.py
Changes which should have been included in #448 are continued here.
=> Miscellaneous improvements in docs

sparse/_common.py, sparse/tests/test_dok.py
=> Fix concatenate/stack for sparse.DOK.

benchmarks/benchmark_matmul.py
This is WIP. More commits incoming.
=> Improve matmul benchmark

azure-pipelines.yml, sparse/_dok.py, sparse/tests/test_dok.py
=> Fix falsely triggered advanced indexing.

benchmarks/benchmark_matmul.py
=> Black formatting in `benchmark_matmul.py`

docs/construct.rst, sparse/_dok.py, sparse/tests/test_dok.py
=> Fix DOK indexing and CI failures.

sparse/_common.py, sparse/_compressed/compressed.py, sparse/_coo/core.py, sparse/_dok.py, sparse/_utils.py, sparse/tests/test_conversion.py, sparse/tests/test_dot.py
=> Fix format conversion bugs.

sparse/_common.py
=> Fixing NaN check bug

sparse/_coo/core.py, sparse/tests/test_coo.py
=> Fix incorrect sparse scalar array.

sparse/_compressed/compressed.py, sparse/tests/test_conversion.py
Hello,
Solved issue 529 in this pull request, please verify the changes.
Fixes #529 
Thanks and Regards,
Sarvesh
=> Solved Issue 529

docs/conduct.rst, docs/contributing.rst, sparse/_common.py, sparse/_utils.py, sparse/tests/test_coo.py
Using the dense_sparse tensordot benchmark for 100 runs:
New: 0.09302s +- 0.001313s
Old: 0.186462s +- 0.004102s
Closes #536
=> removed transpose before _dot_ndarray_coo function

docs/conf.py, docs/construct.rst, docs/operations.rst, docs/quickstart.rst, sparse/_coo/common.py, sparse/tests/conftest.py, sparse/tests/test_compressed_2d.py, sparse/tests/test_coo.py, sparse/tests/test_elemwise.py
=> Fix nanmean for complex arrays.

sparse/_coo/core.py, sparse/tests/test_elemwise.py
=> Fix misfire of DeprecationWarning.

sparse/_sparse_array.py, sparse/tests/test_elemwise.py
=> Fix upcast on in-place.

sparse/_common.py, sparse/_coo/core.py, sparse/tests/test_coo.py
This PR adds `squeeze` method to COO format.
=> API: Add `squeeze` method to COO

examples/spmv_add_example.py, examples/spmv_example.py
Hi @willow-ahrens @hameerabbasi,
This is the third one (and last) PR with an example: SpMV. Here it looks that Finch is x50 times slower than Numba/Scipy.
Here's a debug mode plan:
<details>
```julia
Executing:
:(function var"##compute#289"(prgm)
begin
V = ((((((((((((((((((((((((((((prgm.children[1]).children[2]).children[1]).children[1]).children[2]).children[1]).children[2]).children[1]).children[1]).children[1]).children[1]).children[2]).children[3]).children[1]).children[1]).children[1]).children[2]).children[1]).children[2]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[2]).tns.val::Tensor{DenseLevel{Int64, SparseListLevel{Int64, PlusOneVector{Int32}, PlusOneVector{Int32}, ElementLevel{0.0, Float64, Int64, …
```
=> Add `SpMV` example

ci/Finch-array-api-xfails.txt, pyproject.toml
Needs https://github.com/willow-ahrens/finch-tensor/pull/64
=> Upgrade `finch-tensor`

examples/elemwise_example.py, examples/mttkrp_example.py, examples/sddmm_example.py, examples/spmv_add_example.py, examples/utils.py
This PR adds elemwise examples that got removed from `asv`.
=> Add elemwise examples

.github/workflows/ci.yml
xref https://github.com/JuliaPy/PythonCall.jl/issues/443
=> Workaround for macOS CI

.github/workflows/ci.yml, conftest.py, pyproject.toml, sparse/__init__.py, sparse/mlir_backend/__init__.py, sparse/mlir_backend/_constructors.py, sparse/mlir_backend/_core.py, sparse/mlir_backend/_dtypes.py, sparse/mlir_backend/_memref.py, sparse/mlir_backend/_ops.py, sparse/mlir_backend/tests/conftest.py, sparse/mlir_backend/tests/test_simple.py
POC MLIR backend with:
- CSR and Dense 2D formats
- Simple elemwise addition
=> feat: MLIR backend POC

.coveragerc, .github/workflows/ci.yml, ci/environment.yml, sparse/mlir_backend/_core.py, sparse/mlir_backend/tests/test_simple.py
***
* Merge MLIR backend tests to all others
* Add coverage testing for MLIR Backend
* Use `micromamba-action`.
=> ci: Merge MLIR Backend

sparse/mlir_backend/_common.py, sparse/mlir_backend/_constructors.py, sparse/mlir_backend/_core.py, sparse/mlir_backend/_dtypes.py, sparse/mlir_backend/_memref.py, sparse/mlir_backend/_ops.py, sparse/mlir_backend/tests/conftest.py, sparse/mlir_backend/tests/test_simple.py
***
- **Refactor to allow arbitrary dtypes.**
- **Do refcounting instead of copies.**
- **Actually test multiple dtypes.**
=> feat, perf: Refactor the PoC to support multiple dtypes

ci/environment.yml, pixi.toml, sparse/mlir_backend/__init__.py
This PR upgrades MLIR version to `19.1.0`.
=> MAINT: Upgrade MLIR version

sparse/mlir_backend/__init__.py, sparse/mlir_backend/_conversions.py, sparse/mlir_backend/_ops.py, sparse/mlir_backend/tests/test_simple.py
=> Testing improvements and minor fixes.

ci/Finch-array-api-xfails.txt, sparse/mlir_backend/__init__.py, sparse/mlir_backend/_array.py, sparse/mlir_backend/_conversions.py, sparse/mlir_backend/_ops.py, sparse/mlir_backend/formats.py, sparse/mlir_backend/tests/test_simple.py, sparse/numba_backend/_common.py
***
Introduces format factories to simplify the building of formats without having to fudge with levels.
=> Introduce format factories

docs/operations.md
- Related issue #842 
- Closes #842
***
=> Correct `AUTO_DENSIFY` default value in docs

ci/environment.yml, pixi.toml, pyproject.toml
I will cut a new beta release (`0.16.0b4`) once this one is in.
=> New `finch-tensor` release

sparse/numba_backend/_compressed/compressed.py, sparse/numba_backend/_coo/core.py, sparse/numba_backend/tests/test_conversion.py
=> fix: Fix conversions from non-canonical `scipy.sparse` arrays

.github/workflows/ci.yml
- Closes #574 
***
CodeCov will run only when all of the above steps pass.
=> Running codecov only when tests pass
